version: '3.1'
services:
  db:
    image: mysql
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=telegram
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d